/**
 * build-master.js — turn the Claude-Design "decoded.html" into a parameterized
 * master.html template by:
 *   1. Keeping the entire <style> block intact (the design system),
 *   2. Replacing the hard-coded body with placeholder slots,
 *   3. Adding Google Fonts CDN for Sarabun + JetBrains Mono (the embedded
 *      woff2 blobs were stripped earlier — the design needs these fonts).
 *
 * Run: node build-master.js
 */
"use strict";
const fs = require("fs");
const path = require("path");

const HERE = __dirname;
const SRC  = path.join(HERE, "templates", "extracted", "decoded.html");
const OUT  = path.join(HERE, "templates", "master.html");

const html = fs.readFileSync(SRC, "utf8");

// Pull the second <style>...</style> block (the design system one — the first
// is the empty font @font-face placeholders we already stripped).
const styleMatches = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)];
const designCss = styleMatches[styleMatches.length - 1][1];

// Build the new master.html
const master = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{title}}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
${designCss}

/* ── Print colour fidelity (force gradients / data bars to render in PDF) ── */
*, *::before, *::after {
  -webkit-print-color-adjust: exact !important;
  print-color-adjust: exact !important;
  color-adjust: exact !important;
}
@page { size: A4 portrait; margin: 12mm 10mm; }
@media print {
  .doc { padding: 0; max-width: none; }
  section { break-inside: avoid; page-break-inside: avoid; }
  .kpi-row, .sec-head, .pull, .chart-card, .var-row, .stat-tile { break-inside: avoid; }
  .data-table { page-break-inside: auto; }
  thead { display: table-header-group; }
}
</style>
</head>
<body>
  <div class="toolbar">
    <button onclick="window.print()">Save as PDF</button>
  </div>

  <div class="doc">
    {{content}}

    <footer class="colophon">
      <div>
        <b>Report</b>
        {{title}}<br>
        {{subtitle}}
      </div>
      <div>
        <b>Source data</b>
        {{sourceName}}
      </div>
      <div>
        <b>Issued</b>
        {{today}}<br>
        Generated by NSPB MCP
      </div>
    </footer>
  </div>
</body>
</html>
`;

fs.writeFileSync(OUT, master, "utf8");
console.log(`master.html updated (${Math.round(master.length / 1024)} KB)`);
